kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: kubeapp-production
spec:
  replicas: 1
  template:
    metadata:
      name: kubeapp
      labels:
        app: kubeapp
        env: canary
    spec:
      containers:
      - name: kubeapp
        image: gcr.io/PROJECT_ID/app:1.0
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
        command: ["/app"]
        ports:
        - name: kubeapp
          containerPort: 8080
